// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	likes "mini-project/businesses/likes"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: userID, postID
func (_m *Repository) Create(userID string, postID string) error {
	ret := _m.Called(userID, postID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: userID, postID
func (_m *Repository) Delete(userID string, postID string) error {
	ret := _m.Called(userID, postID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAllLikeByPostID provides a mock function with given fields: postID
func (_m *Repository) DeleteAllLikeByPostID(postID string) error {
	ret := _m.Called(postID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: postID
func (_m *Repository) GetAll(postID string) ([]likes.Domain, error) {
	ret := _m.Called(postID)

	var r0 []likes.Domain
	if rf, ok := ret.Get(0).(func(string) []likes.Domain); ok {
		r0 = rf(postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]likes.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *Repository) GetByID(id string) (likes.Domain, error) {
	ret := _m.Called(id)

	var r0 likes.Domain
	if rf, ok := ret.Get(0).(func(string) likes.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(likes.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserIDAndPostID provides a mock function with given fields: userID, postID
func (_m *Repository) GetByUserIDAndPostID(userID string, postID string) error {
	ret := _m.Called(userID, postID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLikeCount provides a mock function with given fields: postID
func (_m *Repository) GetLikeCount(postID string) (int, error) {
	ret := _m.Called(postID)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(postID)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
