// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	posts "mini-project/businesses/posts"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: Domain
func (_m *Repository) Create(Domain *posts.Domain) (posts.Domain, error) {
	ret := _m.Called(Domain)

	var r0 posts.Domain
	if rf, ok := ret.Get(0).(func(*posts.Domain) posts.Domain); ok {
		r0 = rf(Domain)
	} else {
		r0 = ret.Get(0).(posts.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*posts.Domain) error); ok {
		r1 = rf(Domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAllPostByUserID provides a mock function with given fields: userID
func (_m *Repository) DeleteAllPostByUserID(userID string) error {
	ret := _m.Called(userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: userID
func (_m *Repository) GetAll(userID string) ([]posts.Domain, error) {
	ret := _m.Called(userID)

	var r0 []posts.Domain
	if rf, ok := ret.Get(0).(func(string) []posts.Domain); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]posts.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: postID
func (_m *Repository) GetByID(postID string) (posts.Domain, error) {
	ret := _m.Called(postID)

	var r0 posts.Domain
	if rf, ok := ret.Get(0).(func(string) posts.Domain); ok {
		r0 = rf(postID)
	} else {
		r0 = ret.Get(0).(posts.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, Domain
func (_m *Repository) Update(id string, Domain *posts.Domain) (posts.Domain, error) {
	ret := _m.Called(id, Domain)

	var r0 posts.Domain
	if rf, ok := ret.Get(0).(func(string, *posts.Domain) posts.Domain); ok {
		r0 = rf(id, Domain)
	} else {
		r0 = ret.Get(0).(posts.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *posts.Domain) error); ok {
		r1 = rf(id, Domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
