// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	students "mini-project/businesses/students"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: userDomain
func (_m *Repository) Create(userDomain *students.Domain) (students.Domain, error) {
	ret := _m.Called(userDomain)

	var r0 students.Domain
	if rf, ok := ret.Get(0).(func(*students.Domain) students.Domain); ok {
		r0 = rf(userDomain)
	} else {
		r0 = ret.Get(0).(students.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*students.Domain) error); ok {
		r1 = rf(userDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *Repository) GetByID(id string) (students.Domain, error) {
	ret := _m.Called(id)

	var r0 students.Domain
	if rf, ok := ret.Get(0).(func(string) students.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(students.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, userDomain
func (_m *Repository) Update(id string, userDomain *students.Domain) error {
	ret := _m.Called(id, userDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *students.Domain) error); ok {
		r0 = rf(id, userDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
